// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Message documents */
interface MessageDocumentData {
    /**
     * Message Content field in *Message*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: message.message_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    message_content: prismicT.KeyTextField;
}
/**
 * Message document from Prismic
 *
 * - **API ID**: `message`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MessageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MessageDocumentData>, "message", Lang>;
export type AllDocumentTypes = MessageDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { MessageDocumentData, MessageDocument, AllDocumentTypes };
    }
}
