import Head from 'next/head'
import { useEffect, useState } from 'react';
import styled from 'styled-components';
import { createClient } from 'contentful-management'


export default function Home(props) {
  const [formData, setFormData] = useState({
    message: ''
  });
  const [messageSendState, setMessageSendState] = useState('NOT SENT');
  const [formDisabled, setFormDisabled] = useState(false);
  const [receivedMessage, setReceivedMessage] = useState(undefined);

  const getRandomInt = (min, max) => {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  const client = createClient({
    accessToken: props.CONTENTFUL_MGM_KEY
  });

  const postMessage = (message) => {
    client.getSpace(props.CONTENTFUL_SPACE_ID)
      .then((space) => space.getEnvironment('master'))
      .then((environment) => environment.createEntry('message', {
        fields: {
          messageContent: {
            'en-US': formData.message
          }
        }
      }))
      .then((entry) => {
        setMessageSendState('SUCCESS');
        getRandomMessage();
      })
      .catch((error) => {
        setMessageSendState('FAIL')
      })
  };

  const getRandomMessage = () => {
    getAllMessages((messages) => {
      let totalMessages = messages.length;
      let randomNumber = getRandomInt(0, totalMessages);
      console.log(randomNumber)
      console.log(messages[randomNumber - 1]);
      setReceivedMessage(messages[randomNumber].fields.messageContent['en-US']);

    })
  }

  const getAllMessages = (onMessagesReceived) => {
    client.getSpace(props.CONTENTFUL_SPACE_ID)
      .then((space) => space.getEnvironment('master'))
      .then((environment) => environment.getPublishedEntries({'content_type': 'message'})) // you can add more queries as 'key': 'value'
      .then((response) => onMessagesReceived(response.items))
      .catch(console.error)
  }

  const handleFormSubmit = (e) => {
    e.preventDefault();
    setFormDisabled(true)
    postMessage();
  };

  useEffect(() => {
    console.log(formData)
  }, [formData])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        <form 
          className={`${formDisabled ? 'disabled' : ''}`} 
          onSubmit={handleFormSubmit}
        >
          <div className="form-group">
            <label id="message">Mensaje</label>
            <input 
              type="text" 
              name="message"
              onChange={(e) => {
                setFormData({
                  message: e.target.value
                })
              }}
            />
          </div>
          <button type="submit">Enviar</button>
        </form>
        {receivedMessage && (
          <strong>{receivedMessage}</strong>
        )}
      </StyledMain>
    </div>
  )
}

const StyledMain = styled.main`
  display: flex;
  width: 100vw;
  height: 100vh;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  form {
    display: flex;
    flex-direction: column;
    width: 30rem;
    &.disabled {
      opacity: 0.4;
      pointer-events: none;
    }
    button,
    input {
      height: 2rem;
    }
    .form-group {
      margin-bottom: 1rem;
      display: flex;
      flex-direction: column;
      width: 100%;
      label {
        margin-bottom: 0.5rem;
      }
    }
  }
  strong {
    margin-top: 2rem;
  }
`;

export async function getStaticProps() {

  return ({
    props: {
      CONTENTFUL_MGM_KEY: process.env.CONTENTFUL_MGM_KEY,
      CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID
    }
  })
}